// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPCCp8xPHepeXO8vt2nTvv7Hh0MOCoRVg',
    appId: '1:986216229652:web:5dd193384a0c086983b001',
    messagingSenderId: '986216229652',
    projectId: 'wecare-5c07b',
    authDomain: 'wecare-5c07b.firebaseapp.com',
    storageBucket: 'wecare-5c07b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmbx5oHoQHmAe8qT8oSyapo0TMpgNDXzc',
    appId: '1:986216229652:android:2f4cf16de708097183b001',
    messagingSenderId: '986216229652',
    projectId: 'wecare-5c07b',
    storageBucket: 'wecare-5c07b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Sv5YPTfZIk4DHp4DRxSX76WLNJOotDc',
    appId: '1:986216229652:ios:ac3165572dc36fb583b001',
    messagingSenderId: '986216229652',
    projectId: 'wecare-5c07b',
    storageBucket: 'wecare-5c07b.appspot.com',
    androidClientId: '986216229652-bhjqj46or8jiif4evvnvnhaqnsjbu362.apps.googleusercontent.com',
    iosClientId: '986216229652-5fnu1ghdilnfpup3v13a982oqj4s132u.apps.googleusercontent.com',
    iosBundleId: 'in.nic.faridkot.wecare.wecare',
  );
}
